"""Se activo la capacidad de hacer nulo el valor del id del cliente

Revision ID: c51de8d0cbc6
Revises: ee6fc1e1fba3
Create Date: 2024-07-02 00:24:25.986667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c51de8d0cbc6'
down_revision: Union[str, None] = 'ee6fc1e1fba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
