"""Campo de direccion en la tabla de proveedores

Revision ID: c827bbea8511
Revises: cf90256ba2aa
Create Date: 2024-06-08 12:57:17.146273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c827bbea8511'
down_revision: Union[str, None] = 'cf90256ba2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('address', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'address')
    # ### end Alembic commands ###
