"""Migracion de inicio: Tabla de proveedores con eamil

Revision ID: cf90256ba2aa
Revises: 
Create Date: 2024-06-08 12:46:09.976333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf90256ba2aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'suppliers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'email')
    # ### end Alembic commands ###
